### ISSUE TITLE
 window is not defined ERR when i use SSR (nextjs)

### ISSUE THREAD

**Issue by otthry** [jfangrad/react-dropdown-aria#33]
hey
when i use react-dropdown-aria in nextjs
 window is not defined ERR,,

Can you fix that i can choose Options for not using utiles/useId.ts?
windows variable is not render in SSR when you drawing dropdown ui

plz reply

thanks!

**Comment by jfangrad** [comment]
Hi,

Thanks for the issue. SSR is definitely not something I was thinking about when making that util but you raise a good point, thanks!

Are you actually getting errors when trying to use it via SSR? (if so please post the error here) Or is it just returning the test id for all your dropdowns?

I can make that util simply check if you are in a test env or not instead of checking if the window exists as well.

**Comment by otthry** [comment]
Thankyou for replay

ERROR MESSAGE is 
`./node_modules/react-dropdown-aria/dist/utils/useId.js 6:35
Module parse failed: Unexpected token (6:35)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| var constants_1 = require("./constants");
|     window.document &&
>     window.document.documentElement);
| var isBrowser = process.env.NODE_ENV !== 'test' && isClient;
| var idCount = 0;
`

**Comment by jfangrad** [comment]
@otthry Thanks for posting the error. I have released a new version of the package: `2.0.3`

I have also tested it with nextjs and was able to get it working. Let me know if you have any other issues!

**Comment by otthry** [comment]
thank you  @jfangrad  😭💕💕
